config/routes.rb
CloisterSpaceServer::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :sessions

  get "sign_up" => "users#new", :as => "sign_up"
  resources :users

  resources :games do
    match 'tileInstances/place/:id' => 'tileInstances#update'
    match 'tileInstances/:status' => 'tileInstances#index'

    match 'next' => 'games#next'
    match 'move/:num' => 'games#move'
  end

  root :to => 'games#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloisterSpaceServer</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <link rel="shortcut icon" href="/favicon.ico"/>
  </head>
  <body>

    <div id="user_nav">
      <% if current_user %>
        <div id="nav_game">
          <span class="nav_item"><%= link_to 'MAIN MENU', games_path %></span>
          <span class="nav_item"><%= link_to 'NEW GAME', new_game_path %></span>
          <% if @game and @game.valid? %>
            <span class="nav_item">
              <img src="../images/leftarrow.png"/>
              PREVIOUS GAME
            </span>
            <span class="nav_item blue">
              GAME #<%= @game.id %>
            </span>
            <span class="nav_item">
              NEXT GAME
              <img src="../images/rightarrow.png"/>
            </span>
          <% end %>
        </div>
        <div id="nav_session">
          <span class="nav_item">    
            SIGNED IN AS <span class="blue"><%= current_user.email.upcase %></span>.
            <%= link_to "SIGN OUT?", log_out_path %>              
          </span>
        </div>
      <% else %>
        <div id="nav_session">
          <span class="nav_item">    
            <%= link_to "SIGN UP", sign_up_path %> OR
            <%= link_to "LOG IN", log_in_path %>
          </span>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <p id="notice"><%= notice %></p>
    <p id="error"><%= flash[:error] %></p>
  </body>
</html>